name: flutter_alien
description: A new Flutter package project.
version: 0.0.1
author: deandreamatias
homepage: https://universoflutter.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dart_rss: ^1.1.1+1
  http: ^0.12.2
  xml: ^4.5.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
