name: flutter_alien
description: A new Flutter package project.
version: 0.0.1
author: deandreamatias
homepage: https://universoflutter.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_rss: ^1.1.1+1
  github: ^7.0.3
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  test: ^1.15.7
