name: flutter_alien
description: Get info about Flutter social media
version: 0.1.0
homepage: https://universoflutter.com
repository: https://github.com/flutteruniverse/flutter-alien
issue_tracker: https://github.com/flutteruniverse/flutter-alien/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dart_rss: ^1.1.1+1
  http: ^0.12.2
  xml: ^4.5.0

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
