name: flutter_alien
description: Get info about some social medias. Create to Universo Flutter
version: 0.1.1
homepage: https://universoflutter.com
maintainer: Matias de Andrea (@deandreamatias)

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dart_rss: ^1.1.1+1
  http: ^0.12.2
  intl: ^0.16.1
  xml: ^4.5.0
  youtube_explode_dart: ^1.7.5

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.15.7
