name: flutter_alien
description: Get info about some social medias. Create to Universo Flutter
version: 0.1.4
homepage: https://universoflutter.com
maintainer: Matias de Andrea (@deandreamatias)

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  dart_rss: ^2.0.1
  http: ^0.13.4
  intl: ^0.17.0
  xml: ^5.3.1
  youtube_explode_dart: ^1.11.0

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.21.3
