name: Analyze code

on:
  push:
    branches: [main, develop]
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Test package
    runs-on: macos-latest

    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - name: Flutter action
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 2.10.5
    - name: Install dependencies
      run: flutter pub get
    - name: Code lint analyze
      run: flutter analyze

  deployment:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    name: Deploy package
    runs-on: macos-latest

    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - name: Flutter action
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 2.10.5
    - name: Setup pub credentials
      shell: bash
      env:
        PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
        PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      run: |
        sh ./tools/pub_login.sh
    - name: Check publish warnings
      run: dart pub publish --dry-run
    - name: Publish package
      run: dart pub publish -f

