name: Analyze code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - name: Configure enviroment
      uses: actions/checkout@v2 
    - run: dart .tool/env_service.dart
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: pub get
    - name: Code lint analyze
      run: dart analyze
    - name: Tests
      run: dart test
