name: Analyze code

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Test package
    runs-on: ubuntu-latest
    container:
      image:  google/dart:2.8.0
    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - run: dart .tool/env_service.dart
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: pub get
    - name: Code lint analyze
      run: dart analyze

  deployment:
    if: ${{ github.ref_type == 'tag' }}
    needs: build
    name: Deploy package
    runs-on: ubuntu-latest
    container:
      image:  google/dart:2.8.0

    steps:
    - name: Configure enviroment
      uses: actions/checkout@v3
    - name: Setup pub credentials
      shell: bash
      env:
        PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
        PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
      run: |
        sh ./tools/pub_login.sh
    - name: Check publish warnings
      run: pub publish --dry-run
    - name: Publish package
      run: pub publish -f

